### ISSUE TITLE
Sync Read how should it work

### ISSUE THREAD

**Issue by flazzarini** [mfussenegger/knx#1]
Hi there, in the doc string of `Connection.read` it is written that this function would send all Received Telegrams to a `knx listener`, but in the `Connection` class you can't pass such a listener nor can you create such an instance? Can you explain in more detail how this is supposed to work.

Thanks a lot in advance :)

**Comment by mfussenegger** [comment]
You'd need to do both, create a AsyncKnx class with which you listen in a event loop and a Connection class.

Something like this (untested):

```
import asyncio
from knx import AsyncKnx, connect, coroutine
from threading import Thread
from time import sleep


def call_read():
    with connect() as c:
        while True:
            sleep(2)
            c.read('0/1/20')


@coroutine
def logger():
    while True:
        line = (yield)
        print(line)

t = Thread(target=call_read)
t.daemon = True
t.start()

knx = AsyncKnx()
loop = asyncio.get_event_loop()
loop.run_until_complete(knx.listen(logger()))
```

Hope that helps.
I'm still not fully settled on the API so I'm open for suggestions.

**Comment by flazzarini** [comment]
Hi there, yes this actually helped me figuring out how I could integrate this library into my project. Thanks a bunch!

**Comment by mfussenegger** [comment]
I've finally added an example which hopefully shows how the listen/read stuff is supposed to work. See https://github.com/mfussenegger/knx/pull/8
