### ISSUE TITLE
Sintax error while compiling in c9.io

### ISSUE THREAD

**Issue by Jujonet** [mfussenegger/knx#12]
Hi,
Trying to make a simple telegram bot for controlling my house and using c9.io as workspace
When installing the libraries get the following error:

`jujonet:~/workspace $ sudo pip install knx
Downloading/unpacking knx
  Downloading knx-0.3.0-py2.py3-none-any.whl
Installing collected packages: knx
Compiling /tmp/pip_build_root/knx/knx.py ...
  File "/tmp/pip_build_root/knx/knx.py", line 237
    data = yield from reader.read(100)
                    ^
SyntaxError: invalid syntax

Successfully installed knx
Cleaning up...`

Not sure if this is just related to cloud9.

Regards

Julio

**Comment by mfussenegger** [comment]
You need to have python 3.4 or python 3.5
Looks like you're using an earlier version in which `yield from` is a syntax error.
