### ISSUE TITLE
How can I calculate these values?

### ISSUE THREAD

**Issue by Emenc** [mfussenegger/knx#14]
How can I calculate the decimal value of a 2 bytearray. 
As input I get a bytearray (first part of the equation) = result from 'telegram_logger.py
I parse this into 2 bytes (middle part of the equation). 
I know what the results are from ETS (last part of the equation).

bytearray(b'\x11\xc7') = b'11c7' = 18.2
bytearray(b'\x07\x1b') = b'071b' = 18.19
bytearray(b'>Y') = b'3e59' = 2080
bytearray(b'>Z') = b'3e5a' = 2081.28

**Comment by mfussenegger** [comment]
Do you know the DPT of those?

The first two look like DPT 9.xxx
Decoding it would look something like this:

```
data = bytearray(b'\x11\xc7')
signed = ((data[0] & 0x80) >> 7) == 1
m = ((data[0] & 0x07) << 8) | data[1]

val = m
power = (data[0] & 0x78) >> 3
calc = 0.01 * val

print(calc * 2 ** 2)
```

I think https://github.com/XKNX/xknx/tree/master/xknx/knx and https://github.com/lifeemotions/knx.net/tree/master/src/KNXLib/DPT have proper decoding implementation.

Personally I've only lights which return 0 or 1 - so I didn't bother to add dpt encoding/decoding to this library but I guess I'd accept contributions
