### ISSUE TITLE
knx write

### ISSUE THREAD

**Issue by rpoglitsch** [mfussenegger/knx#15]
hallo,
ist es möglich mit deinem plugin ein dpt 16.00 (ASCII) an den bus zu senden!
bei mir läuft das immer in einen fehler, auch wenn ich vorher korrekt in ein bytearray umrechne und dieses der write funktion übergebe!

**Comment by mfussenegger** [comment]
Should be possible if the `writer` is used directly and if the encoding is done manually. See https://github.com/mfussenegger/knx/pull/13/files#diff-63c0c9575fd31ec470371506a4254035R215

I've been wanting to take a look at how I could integrate more flexible dpt encoding/decoding, but it's not high on my todo list and there are too many other things on it.
