### ISSUE TITLE
Data types

### ISSUE THREAD

**Issue by ghost** [mfussenegger/knx#2]
I have started trying out the examples. It seems to me that the Async example does not handle some data types correctly.

One example of the percentage data type. From ETS:

![telegram](https://cloud.githubusercontent.com/assets/15005583/10324822/f8b6d900-6c8c-11e5-898d-aac43a72b014.jpg)

From the example python script:

Telegram(src='2/1/254', dst='0/4/36', value='0')

The value should be $CC or 80%.

The source address appears incorrect, as well.

/Per

**Comment by mfussenegger** [comment]
Thanks for reporting.
Seems like the binary decoder doesn't handle those values correctly (which is probably to be expected as I only tested it with 0/1 values)

But given the data in the screenshot I should be able to extend it.
Hopefully I can get around to do that on the weekend

**Comment by ghost** [comment]
Having done some debugging printouts in telegram_decoder, and browsing various KNX frame specifications my conclusions are:
- If the data is of a type that is at most 6 bits, it is in the 6 LSB of data[9]
- Otherwise the data is in data[10:]. Can be up to 14 bytes.
- Sender adress has a different encoding scheme than destination - it is 4/4/8 bits for Area/Line/Device, whereas destination is 4/3/8 bits for Main/Middle/Sub Group. The MSB bit of  dst is unused. (Sender address should be written with dots, not slashes.)

Can't help with coding though... Started learning Python a couple of weeks ago.

**Comment by mfussenegger** [comment]
I've fixed the src address stuff in master.

But I'm still looking into how to read the values correctly. Would like to get this right but most docs that I can find about the data format are pretty cryptic.
So it will take a little while longer until I can solve that

**Comment by ghost** [comment]
I see now that my last comment was a bit wrong. data[9] should be buf[9] and data[10:] should be buf[10:]

It is hard to find one document that describes the protocol(s) involved clearly. I think I have grasped it:
• Data that is 6 bits or less is in buf[9]
• Data that is one byte or more starts in buf[10]
• Since the length of the telegram(less two) is in buf[1], the data is in buf[9] if buf[1] is 8. If buf[1] is 9 or more, the data starts in buf[10]. The length of the data is buf[1]-8
• A recipient on the KNX bus knows what data type is expected on a certain group address, and decodes it depending on the application. There are very many data types.
• I think the library should deliver the raw data, but picked out correctly from buf[9] or buf[10:], respectively. The application would have to decode it further depending on the data type
Some examples, that I sent from ETS, and printouts of i and buf[i]
![image](https://cloud.githubusercontent.com/assets/15005583/10466164/075e18cc-71f3-11e5-929e-a5b7ecc4be46.png)

Example 1:
0 00
1 08
2 00
3 27
4 11
5 FE
6 00
7 07
8 00
9 83
Example 2:
0 00
1 09
2 00
3 27
4 11
5 FE
6 00
7 07
8 00
9 80
10 03
Example 3:
0 00
1 0A
2 00
3 27
4 11
5 FE
6 00
7 07
8 00
9 80
10 03
11 03
Example 4:
0 00
1 0B
2 00
3 27
4 11
5 FE
6 00
7 07
8 00
9 80
10 03
11 A3
12 03

**Comment by ghost** [comment]
The knx plugin of smarthome.py is illuminating to study.

https://github.com/mknx/smarthome/blob/master/plugins/knx/__init__.py
https://github.com/mknx/smarthome/blob/master/plugins/knx/dpts.py

In the smarthome.py setup there is a configuration file to keep track of what data type is associated with each group address (as well as to configure what action should be taken based on events associated with the group addresses).

In a general purpose library I do not think it is necessary to do the data type decoding.

**Comment by mfussenegger** [comment]
Thanks I was aware of smarthome.py =)

I actually had hoped that I had missed something and that the dpt value was actually part of a telegram. Seems that is not the case.

I've now changed the decoder so that it will emit Telegrams with value as raw-data if it contains more than 1 byte. 
See https://github.com/mfussenegger/knx/pull/4

But I'm not yet sure if that will work for all cases as the raw value is change to either 0 or 1 in case there is just 1 byte.

**Comment by ghost** [comment]
I will test it tonight.

I guess something needs to be done about writing to a group address. The write function needs to be told whether to encode the data as a data type with max 6 bits or how many bytes of data should be sent.

**Comment by ghost** [comment]
I have now tested the decoder changes - working as expected with raw data 6 bits or less, and also with raw data of 1, 2, 3 or 4 bytes, and indeed with a 14 character text, all sent from ETS.

**Comment by mfussenegger** [comment]
Glad to hear that.
Does the current write function also work for you or would that need to support multiple bytes too?

**Comment by ghost** [comment]
As far as I can understand (and test), I do not think the current write function supports any data type with more than 6 bits. I use many data types with single bytes - e.g. dimmer values, sound volume values.

**Comment by mfussenegger** [comment]
Sorry I kind of lost track of this.

Would it work for you if the write function would also accept a bytestring or bytearray?

**Comment by ghost** [comment]
Yes, that should work. Then it is up to the application to adapt its data, which should not be a problem, and also economical in simple cases. 

In addition to the payload data, the write function needs to be told whether the data type is up to 6 bits or more - but it does not need to know anything more than that regarding data types. (Or there could be two separate write functions.)

**Comment by mfussenegger** [comment]
This should finally be solvable in user applications by using the custom encode function introduced in https://github.com/mfussenegger/knx/commit/9be26d1613872dc5b943c72aba3e2e66915a6e58
